services:
  backend:
    image: girinmaster/chatbot-backend:lastest
    env_file:  # 아래 설정을 추가하면 .env 파일의 변수들이 자동으로 주입됩니다.
      - .env
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///AI.db

  frontend:
    image: girinmaster/chatbot-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend